# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: logo.jpg

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('https://t.alcy.cc/pc/')"

# Particle theme icon is adopts the ant design vue icons
# Linkï¼šhttps://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  ä¸»é¡µ:
    icon:
      name: home
      theme: filled
    src: /
  å…³äº:
    icon:
      name: idcard
      theme: filled
    src: /about # å½“ä½ çš„åšå®¢rootä¸º '/' æ—¶
  Wiki:
    icon:
      name: book
      theme: filled
    src: 'https://wiki.cn86.dev/'
  æ‹“æ‰‘å›¾:
    icon:
      name: apartment
      theme: outlined
    src: 'http://cn86.lzteam.cloud/tracert.php' 
  è®ºå›:
    icon:
      name: message
      theme: outlined
    src: 'https://bbs.cn86.dev'
# side info card
card:
  enable: true
  description: ["å¿ƒæ‰€æƒ³", "çš†å¯å¾€"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/chun-qiucc/cn86-hexo
    bilibili:
      icon:
        type: antd-icon
        name: youtube
        theme: filled
        src:
      link: https://space.bilibili.com/183450641
  friend_links:
    ğŸŒ¸æ˜¥æ¨±äº‘è®¡ç®—ğŸŒ¸: https://www.haruzakura.com
    æ˜¥ç§‹çš„åšå®¢: https://code.cq.cn
    LuocyNET: https://www.luocynet.com/
    LZTeamSE: https://www.lzteam.cloud/

# footer info
footer:
  since: 2024
  # Customize the server domain name ICP
  ICP:
    enable: false
    code: 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: hexo-theme-particle # The name of repository of store comments
  owner: korilin # GitHub repo owner
  admin: korilin # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: night
